### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by Akuli** [Moosems/pyeditorconfig#1]
350 lines of hacky code needs some automated tests. Fortunately for you, you can steal tests from Porcupine too.

**Comment by Moosems** [comment]
:D No idea how to implement tests so I could use a hand here

**Comment by Akuli** [comment]
The typical thing to use is `pytest`, which is also what Porcupine uses. This is a simple and straight-forward project, so you can pretty much follow any reasonable `pytest` tutorial.
